# Generated by Django 3.1.5 on 2021-01-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0002_post_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
