# Generated by Django 3.1.5 on 2021-01-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0003_remove_post_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_hidden',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hidden_by',
        ),
    ]
